### ISSUE TITLE
README shows npm install but preinstall requires yarn

### ISSUE THREAD

**Issue by hjr3** [BowlingX/ra-postgraphile#13]
Hi,

The README hints that one can use npm to install this package, but the [preinstall](https://github.com/BowlingX/ra-postgraphile/blob/353e6cfac642b8c70d97882b493e86469effe9c5/package.json#L8) script throws an error if I am not using yarn. Should this package allow npm installations?

I worked around this for the moment with `npm i ra-postgraphile --ignore-scripts`.

**Comment by BowlingX** [comment]
hi :) thank you for the report. I will remove the check, as it's only required for development.
