### ISSUE TITLE
Unable to pass options to buildGraphQLProvider

### ISSUE THREAD

**Issue by hjr3** [BowlingX/ra-postgraphile#15]
I want to pass the [introspection](https://github.com/marmelab/react-admin/tree/master/packages/ra-data-graphql#introspection-options) option to `buildGraphQLProvider` but [src/factory.ts](https://github.com/BowlingX/ra-postgraphile/blob/dde1f403e120924c07b11d809b6738b458563dc0/src/factory.ts#L6) does not expose a way to send arbitrary options to `buildGraphQLProvider`.

I have a fork where I solved my immediate case:

```ts
export const factory = (
  client: any,
  options: ProviderOptions = { queryValueToInputValueMap: {} },
  introspection?: any
) => { ... }
```

I can PR that, but I imagine that we will want to solve the general problem. If we can decide on the interface, then I can submit a PR.

**Comment by BowlingX** [comment]
Hi :) Thank you for reporting this!
I think the interface you posted works well (with the additional introspection parameter).

I don't see other parameters currently that would make sense. But instead we could also create another options parameter that passes everything to the underlying `buildGraphQLProvider` method, what do you think?

e.g.

```
interface GraphqlProviderOptions { 
   introspection?: any // instead of any we could also go more into details here with types, queries etc.
}
```

Thank you

**Comment by hjr3** [comment]
I like it!

Let me work on it and send up a PR. I will create a `GraphqlProviderOptions` type and make `introspection` have a more narrow type than any.
