### ISSUE TITLE
Support other basic filter types?

### ISSUE THREAD

**Issue by braco** [BowlingX/ra-postgraphile#20]
Hi, I'm just evaluating postgraphile and react-admin for the first time and ran into an issue trying to get a boolean filter setup:

`<BooleanInput source="deleted" defaultValue={false} />`

I'm expecting that to produce this in the query:
`condition: {deleted: false}`

but it throws this error: `Error: Filter for type Boolean not implemented.` from https://github.com/BowlingX/ra-postgraphile/blob/master/src/filters.ts#L34

Are basic types like this not supported for some deliberate reason or just due to time constraints?

**Comment by BowlingX** [comment]
Hi :). Indeed filtering is a topic that is not fully implemented yet. But I will add boolean filters :).
