### ISSUE TITLE
How to fetch function response using ra-postgraphile in react admin?

### ISSUE THREAD

**Issue by praseetha-nair** [BowlingX/ra-postgraphile#22]
Hi,

I have a created a function as follows,

> mutation getOkrDcm {
      getOkrDcm(input: {asset: 4}) {
    results {
      assetId
      id
      keyResult
      objectiveName
    }
    clientMutationId
  }
}

How can I show the results in react admin page using ra-postgraphile dataprovider?

**Comment by BowlingX** [comment]
Hi :) sorry for the late reply. I would require a bit more information what you want to achieve. In general, you can call any custom mutations in custom components that you use in react-admin, and you can display tabular data from views or functions as well.
