### ISSUE TITLE
Intercept the error api response

### ISSUE THREAD

**Issue by UnniKrishnaPanicker** [BowlingX/ra-postgraphile#27]
I am using ra-postgraphile as dataprovider for react-admin project and i need to intercept the error api response. Is there any error object or function available for that? if yes, Can I get a documentation.

**Comment by BowlingX** [comment]
Hi :) This would be the responsibility of the underlying implementation. apollo-graphql is used internally. Depending where you require the error handling, you could do it for example with a custom error link. See here: https://github.com/marmelab/react-admin/tree/master/packages/ra-data-graphql#options how to setup or customize your apollo client.

**Comment by UnniKrishnaPanicker** [comment]
Thank you for your response,
I have tried [apollo-link-error](https://www.npmjs.com/package/apollo-link-error) dependency for intercepting error api response and that worked for me.
