### ISSUE TITLE
Add support for `nodeId` keys

### ISSUE THREAD

**Issue by saerdnaer** [BowlingX/ra-postgraphile#29]
Right now when using types where the primary key is not named `id` (e.g. `guid`, or `slug`) one runs into following error:
https://github.com/BowlingX/ra-postgraphile/blob/bf77e9c0e2af9262e38199bd42e859c1c2414bdc/src/buildQuery.ts#L73-L82

How much needs to be changed, so the code falls back to the `nodeId` field for these cases? 
c.f. https://www.graphile.org/postgraphile/node-id/

**Comment by BowlingX** [comment]
Hi :) quite a few things actually. It would probably also only work for queries, as patches etc. require the id. 
At least for listing views etc. this would make sense of course and useful. It goes a bit in hand with #23, which should allow to be able to filter certain fields as they might be expensive to query.

What I could add is make types configurable for what fields are queried and then additionally make the id check lazy.

**Comment by affluent-bilby-classifieds** [comment]
This is hey they handle it in [ra-data-hasura](https://github.com/hasura/ra-data-hasura)

##Different Primary Keys

Sometimes the table you are querying might have a primary key other than id. react-admin enforces id to be returned in the response by the DataProvider. But you can configure a different primary key column for specific tables using the config object as below:

```
const config = { 
  'primaryKey': { 
      'tableName': 'primaryKeyColumn', 'tableName2': 'primaryKeyColumn' 
  } 
};

```
