### ISSUE TITLE
How to use stored function for RA mutation.

### ISSUE THREAD

**Issue by UnniKrishnaPanicker** [BowlingX/ra-postgraphile#37]
We have tried out this using useMutation and useDataProvider as suggested in RA documentation.

> Source code :
```
    const dataProvider = useDataProvider();
    dataProvider.create("createPerson", { // createPerson is a stored function.
        data: formvalues,
    }).then(({ data }) => {
        console.log(data);
    }).catch((error) => {
        console.log(error);
    });
```
But getting following error.
```
    TypeError: type is undefined
```

**Comment by BowlingX** [comment]
Hi :) Thank you for your report.
Could you provide the signature of the function? We probably don't support this case yet.

Thank you

**Comment by UnniKrishnaPanicker** [comment]
Hi,
Thank you for your response.
Here I'm adding signature of the function.

```
-- FUNCTION: public.create_person(integer, text, text, text, text, timestamp with time zone, text, text, text, text, text, text, text)
```

Thank you

**Comment by BowlingX** [comment]
I think we won't support custom mutations, as this is already covered by using apollo directly. I don't see the benefit of adding it to the data provider. The data provider's general Idea is to support general types and work on those. You can call your custom mutation with `useMutation` as described here: https://www.apollographql.com/docs/react/data/mutations/#usemutation-api

We will add though additional mapping for types, so you will be able to change what mutation is called for a specific type.

**Comment by UnniKrishnaPanicker** [comment]
Thank you for considering adding additional mappings,  
We are expected to have a type that support for calling stored function.
In mean time we'll check custom mutation from apollo.

Thanks again.

**Comment by christiaanwesterbeek** [comment]
Hmm, this is unfortunate. I've used postgrest for years that [has support](https://postgrest.org/en/stable/api.html#stored-procedures) for custom mutations (using resources like `rpc/<my-function-name>` in RA). So, I hoped to find the feature here as well, but instead saw:

> Type "<my-function-name>" did not exist in the introspection result.
