### ISSUE TITLE
updates set all fields

### ISSUE THREAD

**Issue by pyramation** [BowlingX/ra-postgraphile#60]
I'm using column grants for updates, and cannot set all props that can be selected.  I noticed that during updates, the `patch` field automatically gets all of the values, instead of only the changed values. Would there be a simple way to detect which fields have actually changed before patching?

**Comment by BowlingX** [comment]
Sorry for the late reply. If some fields should not be updated, you could possibly remove them based on your logic within `queryValueToInputValue` see https://github.com/BowlingX/ra-postgraphile#typeconfig-options.

**Comment by pyramation** [comment]
ok great, thanks for the response! Will check this out, cheers!
