### ISSUE TITLE
interval fields are missing from queries and mutations

### ISSUE THREAD

**Issue by pyramation** [BowlingX/ra-postgraphile#63]
I've been working with interval fields, and noticed that they are missing from queries and mutations. 

I'm guessing that this is related to https://github.com/BowlingX/ra-postgraphile/issues/62 and can be solved similarly.

Suggested fix is to generate a generic query for all `interval` fields

```gql
    someFieldThatIsInterval {
        seconds
        minutes
        hours
        days
        years
      }
```

I'm imagining we can find a place in the code where we can look at the non-scalar fields. Is there a part of the code that explicitly skips over non-scalar fields? I imagine this is where we can look, and then add some type of switch to determine if they are `interval` or other special types, and we can begin to create the queries for these, or ignore as the default behavior.

**Comment by pyramation** [comment]
I took a look, perhaps this is the area of interest? https://github.com/BowlingX/ra-postgraphile/blob/master/src/utils.ts#L204-L224

Perhaps this is the place to start looking for special types and return a predefined object (e.g., ` { geojson }` or `{ seconds ... years }`)

**Comment by BowlingX** [comment]
This is related to #62 and can be solved the same way.

**Comment by pyramation** [comment]
I've created a repo to help others learn this through example, I know for me, docs and examples can together provide a lot of context. Here is the repo if you want to try running my example use-case: https://github.com/pyramation/ra-postgraphile-examples

Can you check the syntax, I read the solution you mentioned here: https://github.com/BowlingX/ra-postgraphile/issues/62 but I'm not sure exactly how to configure this. 

here is my first attempt for the `timeRequired` field on `Event` which is an `interval` type, relevant to this issue https://github.com/pyramation/ra-postgraphile-examples/blob/master/client/src/App.js#L22-L52

just for reference, to create a location in the example would look like so:

```gql
mutation CreateLocation {
  createEvent(
    input: {
      event: {
        name: "my event"
        timeRequired: {
          days: 10
          hours: 10
          minutes: 10
          months: 10
          seconds: 1.5
          years: 10
        }
      }
    }
  ) {
    event {
      name
      timeRequired {
        seconds
        minutes
        hours
        days
        months
        years
      }
    }
  }
}
```

**Comment by pyramation** [comment]
just for reference, to create a location in the example would look like so:

```gql
mutation CreateLocation {
  createEvent(
    input: {
      event: {
        name: "my event"
        timeRequired: {
          days: 10
          hours: 10
          minutes: 10
          months: 10
          seconds: 1.5
          years: 10
        }
      }
    }
  ) {
    event {
      name
      timeRequired {
        seconds
        minutes
        hours
        days
        months
        years
      }
    }
  }
}
```

**Comment by BowlingX** [comment]
Hi :) thank you so much; It's already past midnight here, so I will have a deeper look tomorrow.

At first sight, you have to use the `expand` keyword like shown in the tests here:
https://github.com/BowlingX/ra-postgraphile/blob/master/src/__tests__/e2e/dataProvider.typeConfig.spec.tsx#L12

I have not tried that with mutations though yet, for this to work you might need to use `queryValueToInputValue`. The argument calculations are not required, they are used to provide arguments to fields if required (see the test example).

I'm aware that the current readme might not be perfectly well explaining how things work, so I'm grateful for any documentation and examples.

**Comment by pyramation** [comment]
This sounds great! I think `interval` is a super simple one to start with, and we can expand from that example. 

So definitely both queries and mutations aren't happening. If we can demonstrate how to create a custom query/mutation for a new type, I believe all the possible types can be easily added. 

Additionally, we have a few components that my team is building and we'll be totally happy to open source these for the ra-postgraphile community (extension of the graphile community) since graphile is what led me here and I'm super grateful for all the people involved. We just started, but already have uploads, media players, links, and a few more. We can pull these out of our source and add them to examples as we extend it.

**Comment by pyramation** [comment]
ok, I updated the example. Super simple for now: https://github.com/pyramation/ra-postgraphile-examples/commit/aede061cdf9a2d314f2f8f7010d1306957c33c0f

Figured just start with `expand: true`

```js
        const dataProvider = await pgDataProvider(client, {
          typeMap: {
            Interval: {
              expand: true
            },
          },
        });
```

The generated query so far was still missing `timeRequired` field

```gql
query events($offset: Int!, $first: Int!, $filter: EventFilter, $orderBy: [EventsOrderBy!]) {
      events(first: $first, offset: $offset, filter: $filter, orderBy: $orderBy) {
        nodes {
          id
      name
      description
      __typename
    }
    totalCount
    __typename
  }
}
```

Maybe I missed something?

**Comment by BowlingX** [comment]
I am not sure if the type `Interval` is actually correct here. You have to check what type your field is actually of. You get the type with `__typename`. I just used it as example.

**Comment by pyramation** [comment]
Thanks @BowlingX :) 

To verify, in the graphiql explorer I ran a basic query

```gql
query List {
  events  {
    nodes {
      id
      timeRequired {
        __typename
        seconds
        minutes
        hours
        days
        months
        years
      }
    }
  }
}
```

with this result:

```
{
  "data": {
    "events": {
      "nodes": [
        {
          "id": 1,
          "timeRequired": {
            "__typename": "Interval",
            "seconds": 1.5,
            "minutes": 10,
            "hours": 10,
            "days": 10,
            "months": 10,
            "years": 10
          }
        }
      ]
    }
  }
}
```

Then in the docs I found this:

## `Event`

![Screen Shot 2021-06-30 at 8 06 32 PM](https://user-images.githubusercontent.com/545047/124058875-0d5c0180-d9df-11eb-956c-0939a9961f73.png)

## `Interval`

![Screen Shot 2021-06-30 at 8 06 38 PM](https://user-images.githubusercontent.com/545047/124058874-0cc36b00-d9df-11eb-8add-2cc495851c0c.png)

**Comment by BowlingX** [comment]
I checked the example repository; The reason why it does not work is because it uses an old version (v3) of `ra-postgraphile`, you have to upgrade to the latest version (v4) to make this configuration work. I tested it with the latest version and the `timeRequired` is queried.

![image](https://user-images.githubusercontent.com/215671/124143336-55386280-da8b-11eb-8cb1-19894d1c2b9c.png)

I would recommend to add lock files for the example and commit them, otherwise it's possible that you end up with different versions of the dependencies.

**Comment by pyramation** [comment]
Oh wow! Simple fix I totally apologize! That was great and queries are working great. 

I'll try out mutations asap and report back 👍🏻

**Comment by pyramation** [comment]
Everything seems to work well, except when mutations involve updates. It somehow is including `__typename` into the JSON. (even if I completely remove the field that contains an interval).

To reproduce, 

1. create a record in react-admin
2. update the record in the database manually to have `time_required = '1 minute'` or some interval
3. refresh page
4. edit record that has the interval (whether it is displayed or not)

```
 Message: Variable "$input" got invalid value { __typename: "Interval", seconds: 0, minutes: 1, hours: 0, days: 0, months: 0, years: 0 } at "input.patch.timeRequired"; Field "__typename" is not defined by type "IntervalInput"., Location: [object Object], Path: undefined
```

**Comment by pyramation** [comment]
UPDATE: I've fixed the mutation issue with a PR: https://github.com/BowlingX/ra-postgraphile/pull/67

**Comment by BowlingX** [comment]
Thank you :) I merged the PR.
