### ISSUE TITLE
Using BigInt for postgres IDs

### ISSUE THREAD

**Issue by shnads** [BowlingX/ra-postgraphile#7]
Awesome data provider, seems to be working as advertised so far.

I have created an edit view now in RA and my DB schema uses BigInt IDs, but the query that's sent when I open the edit view is sending the ID as Int!?

Do I need to do something here to let the dataprovider know my IDs are BigInt?

**Comment by BowlingX** [comment]
Hi :) thank you for your feedback.
This use case is currently not covered and the data type for the single get request is currently a hardcoded Int!. I will adapt the ID type dedection here and pass the propper type.
