### ISSUE TITLE
Pluralize overriding

### ISSUE THREAD

**Issue by kamiyo** [BowlingX/ra-postgraphile#78]
My postgresql automatically pluralizes by adding 's', even to words that don't pluralize that way, e.g. "musics"

Using `pluralize` in your query builder breaks distinguishing between getList and getOne (because Postgraphile generates "music" and "musics" for single vs list query. Thus, when I try to use a React-Admin resource named "musics", it tries to call the query for "music" and fails because it is sending start and offset params, and I have no way of forcing it to be "musics."

Is there any way to override this, or map it somehow, or allow the user to supply a custom pluralize config.

Thanks.

**Comment by BowlingX** [comment]
Hi :).
In general you have to specify your resources as the singular name; In your case:

```
<Resource name="Music" />
```

Customization in the future might make sense, I will check how that could be implemented.

**Comment by kamiyo** [comment]
Yes I understand that, because it goes through some transformations in the
code. The thing is, "Music" never gets pluralized to "Musics", because it's
in the irregular rules exception (looking through the Pluralize library).
But, postgraphile actually generates "Musics" as the list query, so I'm not
ever able to get it to call the right Graphql query.

If you want to table this, it's ok. I'm actually switching my Graphql
engine to Hasura to try that.

Thanks!

**Comment by BowlingX** [comment]
You can now provide a `pluralize` function, I hope this can help in your usecase.

**Comment by kamiyo** [comment]
Sweet, thanks for the quick update! I'll give it a go.

**Comment by TimKraemer** [comment]
> You can now provide a `pluralize` function (see https://github.com/BowlingX/ra-postgraphile#typeconfig-options), I hope this can help in your usecase.

I'm dealing with a related problem in a table called **Quiz**, which PostGraphile pluralizes correctly to _Quizzes_, but in ra-postgraphile the internal pluralize converts it to _Quizs_

I have to admit, that I don't understand how or where I can apply a custom `pluralize` function, so that it solves my problem.
My dataprovider currently looks like that:

```js
      const myDataProvider = {
        ...dp,
        typeMap: {
          GeometryInterface: {
            expand: true,
          }
        },     
      }
```

My limited understanding of this is, that I have to add a custom `pluralize` function to a type, in the `typeMap`. But which type would that be which affects all potential table names?

I'd appreciate any hints into the right direction!
Tim

**Comment by BowlingX** [comment]
Hello @TimKraemer,

for your Example it should be like this:

```
{
  typeMap: {
     Quiz: {
       pluralize: (name: string) => yourPluralizeMethod(name)
     }
  }
}
```

**Comment by TimKraemer** [comment]
Thank you so much! I can't believe I passed the config the wrong way... 
now it works exactly as described!

for future reference the working pluralize function would be:
```js
WordQuiz: {
    pluralize: () => "WordQuizzes"
}
```
