### ISSUE TITLE
Add BigInt support to filters

### ISSUE THREAD

**Issue by shnads** [BowlingX/ra-postgraphile#8]
Hello again!
The fix for BigInt support when fetching records is working great.

Is it possible to add BigInt to the switch in filters.ts? Currently I get 'Filter for type BigInt not implemented.' when I attempt to filter by a BigInt column.

**Comment by shnads** [comment]
As an aside, is there a downside to using BigInt? My research suggested there's no performance or size penalty with a BigInt primary key, and for the sake of future proofing I chose to go with BigInt, but I'm now regretting that choice a little..

**Comment by benjie** [comment]
Bigint is a fine choice for PK.

**Comment by BowlingX** [comment]
I will have a look :)

**Comment by shnads** [comment]
Thanks legends, effort completely appreciated! The combination of postgraphile + react admin is top notch.
