### ISSUE TITLE
Value "ID_ASC" does not exist in enum (on alternate primary key name column)

### ISSUE THREAD

**Issue by drewwestphal** [BowlingX/ra-postgraphile#93]
Consider a super simple table with a text primary key, e.g. 

`CREATE TABLE IF NOT EXISTS p2.venue
(
    venue_name text COLLATE pg_catalog."default" NOT NULL,
    venue_operator text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT venue_pkey PRIMARY KEY (venue_name)
)
`

Upon trying to view this table with a ListGuesser component, at least, I get the following error:

`Variable "$orderBy" got invalid value "ID_ASC" at "orderBy[0]"; Value "ID_ASC" does not exist in "VenuesOrderBy" enum.`

**Comment by BowlingX** [comment]
Hey :) that's interesting, I did not try the guesser components, but I assume they require a single `id` field?. I will look into that.

**Comment by drewwestphal** [comment]
I can update on this. This error also occurs with the standard <List> component if the sort prop is not filled out. I think it just expects a column named `id` no matter what.

The solution, for now, is to set the `sort` prop on `List` to a column that does exist.

E.g. (expanding on the above) `<List>` becomes `<List sort={field: "venueId", order: "ASC"}>`
